# Migrated from YAML automatically by `alacritty migrate` 2024-03-01
# I've manually inserted some comments that were not migrated by the shitty migration impl

# Colors (Gruvbox dark)

[colors.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[font]
size = 15.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Semibold Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "SemiBold"

# AJN: I added these to support cycling between windows and sessions in tmux
[[keyboard.bindings]]
chars = "\u001B[1;5I"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6I"
key = "Tab"
mods = "Control|Shift"

# I am *constantly* hitting Cmd-W by accident on macOS and killing alacritty
# Turn that shit off.
[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"
